name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu  # Example target
          - x86_64-pc-windows-gnu      # Example target
          - aarch64-unknown-linux-gnu  # Example target

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        components: rustfmt, clippy

    - name: Install additional tools
      run: sudo apt-get install -y musl-tools gcc-aarch64-linux-gnu

    - name: Build
      run: cargo build --release --target ${{ matrix.target }}

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.target }}-build
        path: target/${{ matrix.target }}/release/
